# Generated by ariadne-codegen
# Source: queries

from typing import Annotated, Any, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class ProjectV2Issues(BaseModel):
    rate_limit: Optional["ProjectV2IssuesRateLimit"] = Field(alias="rateLimit")
    organization: Optional["ProjectV2IssuesOrganization"]


class ProjectV2IssuesRateLimit(BaseModel):
    limit: int
    cost: int
    remaining: int
    reset_at: Any = Field(alias="resetAt")


class ProjectV2IssuesOrganization(BaseModel):
    project_v_2: Optional["ProjectV2IssuesOrganizationProjectV2"] = Field(
        alias="projectV2"
    )


class ProjectV2IssuesOrganizationProjectV2(BaseModel):
    items: "ProjectV2IssuesOrganizationProjectV2Items"


class ProjectV2IssuesOrganizationProjectV2Items(BaseModel):
    total_count: int = Field(alias="totalCount")
    page_info: "ProjectV2IssuesOrganizationProjectV2ItemsPageInfo" = Field(
        alias="pageInfo"
    )
    nodes: Optional[List[Optional["ProjectV2IssuesOrganizationProjectV2ItemsNodes"]]]


class ProjectV2IssuesOrganizationProjectV2ItemsPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class ProjectV2IssuesOrganizationProjectV2ItemsNodes(BaseModel):
    id: str
    content: Optional[
        Annotated[
            Union[
                "ProjectV2IssuesOrganizationProjectV2ItemsNodesContentDraftIssue",
                "ProjectV2IssuesOrganizationProjectV2ItemsNodesContentIssue",
                "ProjectV2IssuesOrganizationProjectV2ItemsNodesContentPullRequest",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    field_values: "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValues" = Field(
        alias="fieldValues"
    )


class ProjectV2IssuesOrganizationProjectV2ItemsNodesContentDraftIssue(BaseModel):
    typename__: Literal["DraftIssue"] = Field(alias="__typename")


class ProjectV2IssuesOrganizationProjectV2ItemsNodesContentIssue(BaseModel):
    typename__: Literal["Issue"] = Field(alias="__typename")
    number: int
    title: str
    url: Any
    closed: bool
    milestone: Optional[
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesContentIssueMilestone"
    ]


class ProjectV2IssuesOrganizationProjectV2ItemsNodesContentIssueMilestone(BaseModel):
    title: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesContentPullRequest(BaseModel):
    typename__: Literal["PullRequest"] = Field(alias="__typename")


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValues(BaseModel):
    nodes: Optional[
        List[
            Optional[
                Annotated[
                    Union[
                        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldDateValue",
                        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldIterationValue",
                        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldLabelValue",
                        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldMilestoneValue",
                        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldNumberValue",
                        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldPullRequestValue",
                        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldRepositoryValue",
                        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldReviewerValue",
                        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldSingleSelectValue",
                        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldTextValue",
                        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldUserValue",
                    ],
                    Field(discriminator="typename__"),
                ]
            ]
        ]
    ]


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldDateValue(
    BaseModel
):
    typename__: Literal["ProjectV2ItemFieldDateValue"] = Field(alias="__typename")
    field: Union[
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldDateValueFieldProjectV2Field",
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldDateValueFieldProjectV2IterationField",
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldDateValueFieldProjectV2SingleSelectField",
    ] = Field(discriminator="typename__")
    date: Optional[Any]


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldDateValueFieldProjectV2Field(
    BaseModel
):
    typename__: Literal["ProjectV2Field"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldDateValueFieldProjectV2IterationField(
    BaseModel
):
    typename__: Literal["ProjectV2IterationField"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldDateValueFieldProjectV2SingleSelectField(
    BaseModel
):
    typename__: Literal["ProjectV2SingleSelectField"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldIterationValue(
    BaseModel
):
    typename__: Literal["ProjectV2ItemFieldIterationValue"] = Field(alias="__typename")
    field: Union[
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldIterationValueFieldProjectV2Field",
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldIterationValueFieldProjectV2IterationField",
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldIterationValueFieldProjectV2SingleSelectField",
    ] = Field(discriminator="typename__")
    title: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldIterationValueFieldProjectV2Field(
    BaseModel
):
    typename__: Literal["ProjectV2Field"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldIterationValueFieldProjectV2IterationField(
    BaseModel
):
    typename__: Literal["ProjectV2IterationField"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldIterationValueFieldProjectV2SingleSelectField(
    BaseModel
):
    typename__: Literal["ProjectV2SingleSelectField"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldLabelValue(
    BaseModel
):
    typename__: Literal["ProjectV2ItemFieldLabelValue"] = Field(alias="__typename")


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldMilestoneValue(
    BaseModel
):
    typename__: Literal["ProjectV2ItemFieldMilestoneValue"] = Field(alias="__typename")


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldNumberValue(
    BaseModel
):
    typename__: Literal["ProjectV2ItemFieldNumberValue"] = Field(alias="__typename")
    field: Union[
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldNumberValueFieldProjectV2Field",
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldNumberValueFieldProjectV2IterationField",
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldNumberValueFieldProjectV2SingleSelectField",
    ] = Field(discriminator="typename__")
    number: Optional[float]


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldNumberValueFieldProjectV2Field(
    BaseModel
):
    typename__: Literal["ProjectV2Field"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldNumberValueFieldProjectV2IterationField(
    BaseModel
):
    typename__: Literal["ProjectV2IterationField"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldNumberValueFieldProjectV2SingleSelectField(
    BaseModel
):
    typename__: Literal["ProjectV2SingleSelectField"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldPullRequestValue(
    BaseModel
):
    typename__: Literal["ProjectV2ItemFieldPullRequestValue"] = Field(
        alias="__typename"
    )


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldRepositoryValue(
    BaseModel
):
    typename__: Literal["ProjectV2ItemFieldRepositoryValue"] = Field(alias="__typename")


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldReviewerValue(
    BaseModel
):
    typename__: Literal["ProjectV2ItemFieldReviewerValue"] = Field(alias="__typename")


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldSingleSelectValue(
    BaseModel
):
    typename__: Literal["ProjectV2ItemFieldSingleSelectValue"] = Field(
        alias="__typename"
    )
    field: Union[
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldSingleSelectValueFieldProjectV2Field",
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldSingleSelectValueFieldProjectV2IterationField",
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldSingleSelectValueFieldProjectV2SingleSelectField",
    ] = Field(discriminator="typename__")
    name: Optional[str]


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldSingleSelectValueFieldProjectV2Field(
    BaseModel
):
    typename__: Literal["ProjectV2Field"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldSingleSelectValueFieldProjectV2IterationField(
    BaseModel
):
    typename__: Literal["ProjectV2IterationField"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldSingleSelectValueFieldProjectV2SingleSelectField(
    BaseModel
):
    typename__: Literal["ProjectV2SingleSelectField"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldTextValue(
    BaseModel
):
    typename__: Literal["ProjectV2ItemFieldTextValue"] = Field(alias="__typename")
    field: Union[
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldTextValueFieldProjectV2Field",
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldTextValueFieldProjectV2IterationField",
        "ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldTextValueFieldProjectV2SingleSelectField",
    ] = Field(discriminator="typename__")
    text: Optional[str]


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldTextValueFieldProjectV2Field(
    BaseModel
):
    typename__: Literal["ProjectV2Field"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldTextValueFieldProjectV2IterationField(
    BaseModel
):
    typename__: Literal["ProjectV2IterationField"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldTextValueFieldProjectV2SingleSelectField(
    BaseModel
):
    typename__: Literal["ProjectV2SingleSelectField"] = Field(alias="__typename")
    id: str
    name: str


class ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldUserValue(
    BaseModel
):
    typename__: Literal["ProjectV2ItemFieldUserValue"] = Field(alias="__typename")


ProjectV2Issues.model_rebuild()
ProjectV2IssuesOrganization.model_rebuild()
ProjectV2IssuesOrganizationProjectV2.model_rebuild()
ProjectV2IssuesOrganizationProjectV2Items.model_rebuild()
ProjectV2IssuesOrganizationProjectV2ItemsNodes.model_rebuild()
ProjectV2IssuesOrganizationProjectV2ItemsNodesContentIssue.model_rebuild()
ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValues.model_rebuild()
ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldDateValue.model_rebuild()
ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldIterationValue.model_rebuild()
ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldNumberValue.model_rebuild()
ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldSingleSelectValue.model_rebuild()
ProjectV2IssuesOrganizationProjectV2ItemsNodesFieldValuesNodesProjectV2ItemFieldTextValue.model_rebuild()
