load("@dependix_pytest//:defs.bzl", "py_pytest")

py_pytest(
    name = "test",
    size = "small",
    srcs = [
        "check_options_test.py",
    ],
    deps = [
        "//tools/sphinx_extensions",
    ],
)
