/'
   # *******************************************************************************
   # Copyright (c) 2024 Contributors to the Eclipse Foundation
   #
   # See the NOTICE file(s) distributed with this work for additional
   # information regarding copyright ownership.
   #
   # This program and the accompanying materials are made available under the
   # terms of the Apache License Version 2.0 which is available at
   # https://www.apache.org/licenses/LICENSE-2.0
   #
   # SPDX-License-Identifier: Apache-2.0
   # *******************************************************************************
'/
..
   # *******************************************************************************
   # Copyright (c) 2025 Contributors to the Eclipse Foundation
   #
   # See the NOTICE file(s) distributed with this work for additional
   # information regarding copyright ownership.
   #
   # This program and the accompanying materials are made available under the
   # terms of the Apache License Version 2.0 which is available at
   # https://www.apache.org/licenses/LICENSE-2.0
   #
   # SPDX-License-Identifier: Apache-2.0
   # *******************************************************************************

@startuml

participant "Feature User" as actor
participant "«component» :Sub Component 1" as sc1
participant "«component» :Sub Component 3" as sc3

actor -> sc1: real operation 3 ()
sc1 -> sc3: real operation 9 ()

alt success
    sc3 --> sc1: success
else error
    sc3 --> sc1: error type
end

alt success
    sc1 --> actor: true
else error
    sc1 -> actor: error type
end

@enduml
