..
   # *******************************************************************************
   # Copyright (c) 2025 Contributors to the Eclipse Foundation
   #
   # See the NOTICE file(s) distributed with this work for additional
   # information regarding copyright ownership.
   #
   # This program and the accompanying materials are made available under the
   # terms of the Apache License Version 2.0 which is available at
   # https://www.apache.org/licenses/LICENSE-2.0
   #
   # SPDX-License-Identifier: Apache-2.0
   # *******************************************************************************

@startuml

participant "Feature User" as actor
participant "«component» :Component 2" as m2
participant "«component» :Component 1" as m1

actor -> m2: logical operation 3 ()
m2 -> m1: logical operation 1 ()
m1 --> m2: result

alt success
    m2 --> actor: success
else error
    m2 -> actor: error type
end

@enduml
