load("@dependix_pytest//:defs.bzl", "py_pytest")

py_pytest(
    name = "test_checks",
    size = "small",
    srcs = [
        "test_traceability.py",
    ],
    deps = [
        "//tools/sphinx_extensions",
    ],
)
