# Use the official Python DevContainer image as base
FROM mcr.microsoft.com/devcontainers/python:1.2-3.12

# Install system dependencies
RUN apt update && apt install -y graphviz && rm -rf /var/lib/apt/lists/*
