# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Daily Maintenance

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

on:
  # Runs every day at midnight UTC
  schedule:
    - cron: '0 0 * * *'

  # On changes to this workflow file
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/daily.yml'

  # Manually trigger the workflow from the GitHub UI
  workflow_dispatch: {}

jobs:
  maintenance:
    uses: eclipse-score/cicd-workflows/.github/workflows/daily.yml@829b3e11ccbf924a5782f7bfed647cb1619fdf78 # v0.0.1
