# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Documentation

permissions:
  contents: write
  pages: write
  pull-requests: write
  id-token: write

on:
  pull_request_target:
    types: [opened, reopened, synchronize] # Handles forked PRs
  push:
    branches:
      - main # docs are built only on push to main branch, for feature branches there are PR builds
  merge_group:
    types: [checks_requested]
  release:
    types: [created]

jobs:
  docs-build:
    uses: eclipse-score/cicd-workflows/.github/workflows/docs.yml@c1c90b1a82a1fab0fc202979dde6686b2162d5a8 # v0.0.0
    permissions:
      contents: write
      pages: write
      pull-requests: write
      id-token: write
    with:
      bazel-target: "//:docs -- --github_user=${{ github.repository_owner }} --github_repo=${{ github.event.repository.name }}"
      retention-days: 3
