# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  # Common S-CORE Workflow

  common:
    uses: eclipse-score/cicd-workflows/.github/workflows/on-pr.yml@88cb460c47cb49efeb25cd7b73c8945dd1c5bce2 # on-pr/v0.0.0
    permissions:
      contents: read

  # score repo specific additions:

  lint-commits:
    name: check-commit-messages
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run Gitlint Action
        uses: ./.github/actions/gitlint
        with:
          pr-number: ${{ github.event.number }}
          base-branch: ${{ github.event.pull_request.base.ref }}

  fep-fcp-tests:
    name: fep-fcp-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run FEP FCP bot unit tests
        run: |
          pip install --user -r .github/fep_fcp/requirements.txt pytest
          python -m pytest -p no:cacheprovider .github/fep_fcp
